"use client";

import { useActionState, useEffect, useState, useTransition } from "react";
import {
  acknowledgeTemporaryPasswordAction,
  generateTemporaryPasswordAction,
  provisionMemberDirectlyAction,
} from "@/lib/user-management/actions";
import type { ProvisionMemberActionResult } from "@/lib/user-management/types";
import { FieldError, FormError } from "@/components/master-data/FormError";
import { inputClassName, selectClassName } from "@/components/master-data/fields";
import { Button } from "@/components/ui/Button";
import { TemporaryPasswordReveal } from "./TemporaryPasswordReveal";

const initialState: ProvisionMemberActionResult = {};

const INTERNAL_ROLE_OPTIONS: Array<{ value: "admin" | "viewer"; label: string }> = [
  { value: "admin", label: "Admin" },
  { value: "viewer", label: "Viewer" },
];

// Replaces the old "Undang User" (email-invitation) panel for internal
// staff (Admin/Viewer) — the owner types a name/email/role and a temporary
// password, and the membership exists immediately; there is no invite email
// and no separate accept step. displayName/email/role/temporaryPassword are
// all controlled (not the usual TextField/SelectField uncontrolled
// defaultValue pattern) because the success state below needs their exact
// submitted values to label the password reveal and build the mailto link —
// the server action's return value only ever carries temporaryPassword/
// error/fieldErrors, never an echo of what was submitted.
export function AddInternalUserForm() {
  const [state, formAction, isPending] = useActionState(provisionMemberDirectlyAction, initialState);
  const [isAcknowledging, startAcknowledge] = useTransition();
  const [isGenerating, startGenerate] = useTransition();
  const [displayName, setDisplayName] = useState("");
  const [email, setEmail] = useState("");
  const [role, setRole] = useState<"admin" | "viewer">("viewer");
  const [temporaryPassword, setTemporaryPassword] = useState("");

  function regeneratePassword() {
    startGenerate(async () => {
      const password = await generateTemporaryPasswordAction();
      setTemporaryPassword(password);
    });
  }

  // Generated by default on first render so the owner sees a strong
  // candidate immediately ("Password sementara: generated kuat, tampil")
  // without having to click anything first.
  useEffect(() => {
    regeneratePassword();
  }, []);

  function handleAcknowledge() {
    startAcknowledge(async () => {
      await acknowledgeTemporaryPasswordAction();
    });
    setDisplayName("");
    setEmail("");
    setRole("viewer");
    regeneratePassword();
  }

  if (state.temporaryPassword) {
    return (
      <TemporaryPasswordReveal
        temporaryPassword={state.temporaryPassword}
        accountName={displayName}
        accountEmail={email}
        isAcknowledging={isAcknowledging}
        onAcknowledge={handleAcknowledge}
      />
    );
  }

  return (
    <form
      action={formAction}
      className="flex flex-col gap-4 rounded-lg border border-neutral-200 p-4 dark:border-neutral-800"
    >
      <div className="grid gap-4 sm:grid-cols-2">
        <div className="flex flex-col gap-1">
          <label htmlFor="displayName" className="text-sm font-medium">
            Nama Lengkap
            <span className="text-red-600 dark:text-red-400"> *</span>
          </label>
          <input
            id="displayName"
            name="displayName"
            required
            value={displayName}
            onChange={(event) => setDisplayName(event.target.value)}
            aria-invalid={!!state.fieldErrors?.displayName?.length}
            className={inputClassName}
          />
          <FieldError messages={state.fieldErrors?.displayName} />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="email" className="text-sm font-medium">
            Email
            <span className="text-red-600 dark:text-red-400"> *</span>
          </label>
          <input
            id="email"
            name="email"
            type="email"
            required
            value={email}
            onChange={(event) => setEmail(event.target.value)}
            aria-invalid={!!state.fieldErrors?.email?.length}
            className={inputClassName}
          />
          <FieldError messages={state.fieldErrors?.email} />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="role" className="text-sm font-medium">
            Role
          </label>
          <select
            id="role"
            name="role"
            value={role}
            onChange={(event) => setRole(event.target.value as "admin" | "viewer")}
            aria-invalid={!!state.fieldErrors?.role?.length}
            className={selectClassName}
          >
            {INTERNAL_ROLE_OPTIONS.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </select>
          <FieldError messages={state.fieldErrors?.role} />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="temporaryPassword" className="text-sm font-medium">
            Password Sementara
          </label>
          <div className="flex gap-2">
            <input
              id="temporaryPassword"
              name="temporaryPassword"
              required
              value={temporaryPassword}
              onChange={(event) => setTemporaryPassword(event.target.value)}
              aria-invalid={!!state.fieldErrors?.temporaryPassword?.length}
              className={`${inputClassName} font-mono`}
            />
            <Button type="button" variant="secondary" size="md" loading={isGenerating} onClick={regeneratePassword}>
              Buat Ulang
            </Button>
          </div>
          <FieldError messages={state.fieldErrors?.temporaryPassword} />
        </div>
      </div>
      <FormError error={state.error} />
      <div>
        <Button type="submit" variant="primary" loading={isPending}>
          {isPending ? "Membuat..." : "Buat User"}
        </Button>
      </div>
    </form>
  );
}
